---
title: Wijzig een variabele in een lus
hero_image: images/banner.png
description: Wijzig een variabele in een lus
version: 4
listed: false
copyedit: false
last_tested: "2021-05-12"
steps:
  - 
    title: Inleiding
