title: Change a variable in a loop
hero_image: images/banner.png
description: Change a variable in a loop
version: 4
listed: false
copyedit: false
last_tested: "2021-05-12"
steps:
  - title: Introduction
