---
title: Alterar uma variável em um loop
hero_image: images/banner.png
description: Alterar uma variável em um loop
version: 4
listed: false
copyedit: false
last_tested: "2021-05-12"
steps:
  - title: Introdução
