---
title: Cambiar una variable en un bucle
hero_image: images/banner.png
description: Cambiar una variable en un bucle
version: 4
listed: false
copyedit: false
last_tested: "2021-05-12"
steps:
  - title: Introducción
