---
title: Zmodyfikuj zmienną w pętli
hero_image: images/banner.png
description: Zmodyfikuj zmienną w pętli
version: 4
listed: false
copyedit: false
last_tested: "2021-05-12"
steps:
  - title: Wprowadzenie
