---
title: Changer une variable dans une boucle
hero_image: images/banner.png
description: Changer une variable dans une boucle
version: 4
listed: false
copyedit: false
last_tested: "2021-05-12"
steps:
  - title: Introduction
